# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:          /:title

# Setup
baseurl:          /lanyon/
title:            ನಲ್ಲಿಕಾಯಿ
tagline:          'ನಂತರದ ಸಿಹಿ'
description:      '<a target="_blank" href="http://nallikayi.com">ನಲ್ಲಿಕಾಯಿ ಪಾಡ್ಕ್ಯಾಸ್ಟ್</a> ಕೇವಲ ಧ್ವನಿ ಮಾಧ್ಯಮಕ್ಕಾದರೆ, ಅಕ್ಷರಗಳ ಸಿಹಿ ಇಲ್ಲಿದೆ'
url:              http://article.nallikayi.com

author:
  name:           'Sharath D T'
  url:            https://www.facebook.com/sharu725

paginate:         5

# Custom vars
version:          0.8.2


github:
  repo:           
