# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:          /:title

# Setup
baseurl:          /lanyon/
title:            ನಲ್ಲಿಕಾಯಿ
tagline:          'ನಂತರದ ಸಿಹಿ'
description:      '<a target="_blank" href="http://nallikayi.com">ನಲ್ಲಿಕಾಯಿ ಪಾಡ್ಕ್ಯಾಸ್ಟ್</a> ಕೇವಲ ಧ್ವನಿ ಮಾಧ್ಯಮಕ್ಕಾದರೆ, ಅಕ್ಷರಗಳ ಸಿಹಿ ಇಲ್ಲಿದೆ'
url:              

author:
  name:           'Sharath D T'
  url:            https://www.facebook.com/sharu725

paginate:         5

# Custom vars
version:          0.8.2


github:
  repo:           

authors:
  sharathdt:
    display_name: ಶರತ್ ಡಿ.ಟಿ
    gravatar: https://raw.githubusercontent.com/sharu725/lanyon/gh-pages/public/img/sharathdt.jpg
    email: mailto:sharath.dt@gmail.com
    web: http://webjeda.com/
    facebook: https://www.facebook.com/sharu725
    twitter: https://twitter.com/sharathdt
    github: sharu725
    
  bharathibv:
    display_name: ಭಾರತಿ ಬಿ.ವಿ
    gravatar: https://raw.githubusercontent.com/sharu725/lanyon/gh-pages/public/img/bharathi-bv.jpg
    email: mailto:bvbkoll@gmail.com
    web: 
    facebook: https://www.facebook.com/bharathi.bv.5
    twitter: 
    github: 