# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
baseurl:          /lanyon/
title:            ನಲ್ಲಿಕಾಯಿ
tagline:          'ನಂತರದ ಸಿಹಿ'
description:      '<a target="_blank" href="http://nallikayi.com">ನಲ್ಲಿಕಾಯಿ ಪಾಡ್ಕ್ಯಾಸ್ಟ್</a> ಕೇವಲ ಧ್ವನಿ ಮಾಧ್ಯಮಕ್ಕಾದರೆ, ಅಕ್ಷರಗಳ ಸಿಹಿ ಇಲ್ಲಿದೆ'
url:              http://lanyon.getpoole.com

author:
  name:           'Sharath D T'
  url:            https://www.facebook.com/sharu725

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           
